apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: web2
  namespace: webapplication
spec:
  containers:
  - image: httpd:alpine3.20
    name: web2-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
