apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginimage1
  name: nginimage1
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
