apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myspace
  name: myspace
  namespace: s
spec:
  containers:
  - args:
    - nginx
    image: nginx
    name: myspace
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
